### ISSUE TITLE
Problem with result!

### ISSUE THREAD

**Issue by Oqilkhon** [alyyousuf7/Weaver#10]
Computer version and real knitted version no match. Real knitted version getting very dark than program version. What size of image need to be for knitting portrait on the cyrcle with 50 cm diameter. What should be **int cropped_size = 640** and image resolution.
For example i have image 2000x2000 pixels, need i crop image for knitting cyrcle frame with 50 cm diameter?

**Comment by alyyousuf7** [comment]
Can you share a picture of the simulated version and the real version?

**Comment by Oqilkhon** [comment]
![1](https://user-images.githubusercontent.com/68508029/92936454-85166b00-f463-11ea-8c77-6fb29f710e92.jpg)

Left side program version
Right side real version

**Comment by alyyousuf7** [comment]
@Oqilkhon, I think the issue is not with the `cropped_size` variable but with the wrong simulation of thread thickness you've used.

There is a way to better simulate the thread you have used. I'm assuming that you've used the `example01` to generate the result. Please try to change the last parameter (which is set to 25 currently) of the following line to a higher value:
```
WeaveConfig config = new WeaveConfig(3000, 0, 35, color(color(0, 0, 0), 25));
```

This value is called the `draw_color` value. This is responsible to draw the thread on the simulation with a particular intensity. Higher the value, higher the intensity. The maximum value for `draw_color` can be 255.
High intensity of this value will simulate the thickness of the thread used.

Once your simulation and the actual result matches, you can use the same `draw_color` value to generate new results.

**Comment by Oqilkhon** [comment]
This is the configuration which was made this portrait, 

 new WeaveConfig(3000, 0, 35, color(color(0, 0, 0), 30)),

You recommend to change 30 to 25 yes, am i right?

**Comment by alyyousuf7** [comment]
No, change it to higher than your current value until the simulation matches your actual result.

**Comment by Oqilkhon** [comment]
Ok i will try to increase this value, thank You very much!

**Comment by alyyousuf7** [comment]
Once you've got the `draw_color` value corrected, you can generate new results with correct number of threads.

**Comment by Oqilkhon** [comment]
Ok understand, thanks a lot
